package com.luciferdennica.qrtools.util

import android.content.ContentValues
import android.content.Context
import android.content.Intent
import android.graphics.Bitmap
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.RectF
import android.graphics.pdf.PdfDocument
import android.net.Uri
import android.os.Build
import android.os.Environment
import android.provider.MediaStore
import androidx.core.content.FileProvider
import java.io.File
import java.io.FileOutputStream

object PdfExporter {

    /**
     * Создаёт PDF с QR-кодом в центре страницы A4 (или Letter).
     * Сохраняет в Загрузки и возвращает URI для шаринга.
     */
    fun exportToPdf(
        context: Context,
        qrBitmap: Bitmap,
        content: String,
        title: String = "QR Tools"
    ): Uri? {
        val pdf = PdfDocument()

        // A4 в точках (72 dpi): 595 x 842
        val pageWidth = 595
        val pageHeight = 842
        val pageInfo = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, 1).create()
        val page = pdf.startPage(pageInfo)
        val canvas = page.canvas

        // Белый фон
        canvas.drawColor(Color.WHITE)

        val paint = Paint().apply {
            isAntiAlias = true
            color = Color.BLACK
        }

        // Заголовок
        val titlePaint = Paint().apply {
            isAntiAlias = true
            color = Color.BLACK
            textSize = 24f
            textAlign = Paint.Align.CENTER
            isFakeBoldText = true
        }
        canvas.drawText(title, pageWidth / 2f, 60f, titlePaint)

        // QR — 400x400 по центру
        val qrSize = 400
        val qrLeft = (pageWidth - qrSize) / 2f
        val qrTop = 100f
        val destRect = RectF(qrLeft, qrTop, qrLeft + qrSize, qrTop + qrSize)

        // Рамка вокруг QR
        val framePaint = Paint().apply {
            isAntiAlias = true
            style = Paint.Style.STROKE
            strokeWidth = 2f
            color = Color.LTGRAY
        }
        canvas.drawRect(
            RectF(qrLeft - 20f, qrTop - 20f, qrLeft + qrSize + 20f, qrTop + qrSize + 20f),
            framePaint
        )

        canvas.drawBitmap(qrBitmap, null, destRect, paint)

        // Текст под QR
        val textPaint = Paint().apply {
            isAntiAlias = true
            color = Color.DKGRAY
            textSize = 10f
            textAlign = Paint.Align.CENTER
        }
        val shortContent = if (content.length > 70) content.take(70) + "…" else content
        canvas.drawText(shortContent, pageWidth / 2f, qrTop + qrSize + 50f, textPaint)

        // Подвал
        val footerPaint = Paint().apply {
            isAntiAlias = true
            color = Color.GRAY
            textSize = 9f
            textAlign = Paint.Align.CENTER
        }
        canvas.drawText(
            "Generated by QR Tools",
            pageWidth / 2f,
            pageHeight - 30f,
            footerPaint
        )

        pdf.finishPage(page)

        // Сохраняем
        val uri = savePdf(context, pdf)
        pdf.close()
        return uri
    }

    private fun savePdf(context: Context, pdf: PdfDocument): Uri? {
        val fileName = "qrtools_${System.currentTimeMillis()}.pdf"

        return if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
            val values = ContentValues().apply {
                put(MediaStore.Downloads.DISPLAY_NAME, fileName)
                put(MediaStore.Downloads.MIME_TYPE, "application/pdf")
                put(MediaStore.Downloads.RELATIVE_PATH, Environment.DIRECTORY_DOWNLOADS + "/QRTools")
            }
            val uri = context.contentResolver.insert(
                MediaStore.Downloads.EXTERNAL_CONTENT_URI, values
            ) ?: return null

            context.contentResolver.openOutputStream(uri)?.use { out ->
                pdf.writeTo(out)
            }
            uri
        } else {
            @Suppress("DEPRECATION")
            val dir = File(
                Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS),
                "QRTools"
            )
            if (!dir.exists()) dir.mkdirs()
            val file = File(dir, fileName)
            FileOutputStream(file).use { out ->
                pdf.writeTo(out)
            }
            FileProvider.getUriForFile(
                context,
                "${context.packageName}.fileprovider",
                file
            )
        }
    }

    /** Открывает системное меню «Поделиться» для PDF-файла. */
    fun sharePdf(context: Context, uri: Uri) {
        val intent = Intent(Intent.ACTION_SEND).apply {
            type = "application/pdf"
            putExtra(Intent.EXTRA_STREAM, uri)
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
        context.startActivity(Intent.createChooser(intent, null))
    }
}
